Happy_T_Education_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('camp/', include('camp.urls')),
    path('course/', include('course.urls')),
    path('event/', include('event.urls')),
    path('personal/', include('personal.urls')),
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
]

camp/urls.py
from django.urls import path

from . import views

app_name = 'camp'

urlpatterns = [
    path('campList/', views.List, name='List'),
    path('campDetail/', views.Detail, name='Detail'),
    path('new/', views.new, name='new'),
    path('join/', views.join, name='join'),
]

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('course/', views.course, name='course'),
    path('problem/', views.problem, name='problem'),
    path('new/', views.new, name='new'),
    path('detail/', views.detail, name='detail'),
    path('detail/check/', views.check, name='check'),
]

event/urls.py
from django.urls import path

from . import views

app_name = 'event'

urlpatterns = [
    path('', views.event, name='event'),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
]

personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.userProfile, name='userProfile'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/saveAccount/', views.saveAccount, name='saveAccount'),
    path('login/authenticateAccount/', views.authenticateAccount, name='authenticateAccount'),
    path('log_out/', views.log_out, name='log_out'),
]

index/templates/base.html
<!-- header.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC|Open+Sans&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/ba871390e4.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'pic/icon.png' %}">
    <title id = "title">
        {% block title %} {% endblock %}
    </title>
    {% block script %} {% endblock %}
</head>
<body>
    {% include 'header.html' %}
    {% block content %} {% endblock %}
    {% include 'footer.html' %}
    {% block bodyScript %} {% endblock %}
</body>
</html>

index/templates/footer.html
<!-- footer.html -->
<footer class="color">
    <nav class="navbar ">
    <div class="container-fluid">          
        <div class="col-md-4 text-center">
            <br>
            <p>快來加入快樂T一起學習吧！</p>  
        </div>
        <div class="col-md-4">
        </div>
        <div class="col-md-4 text-center">
            <p>Copyright©快樂T版權所有</p>
        </div>
    </div>
</footer>

index/templates/header.html
<!-- header.html -->
<header class="color">
  <div class="container ">        
      <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse  " id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item ">
                      <a class="nav-link active" aria-current="page" href="{% url 'index:index' %}"><i class="fas fa-home"></i>主頁</a>
                  </li>
                  {% if is_authenticated %}
                  <li class="nav-item dropdown">
                      <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fas fa-book-open"></i>學習
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'course:course' %}">課程</a></li>
                        <li><a class="dropdown-item" href="{% url 'course:problem' %}">題目問答</a></li>
                      </ul>
                    </li>

                  <li class="nav-item">
                      <a class="nav-link active" href="{% url 'camp:List' %}"><i class="fas fa-campground"></i>營隊</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link active" href="{% url 'event:event' %}"><i class="fas fa-newspaper"></i>時事</a>
                  </li>
                  <li class="nav-item " >
                      <a class="nav-link active" href="{% url 'personal:userProfile' %}"><i class="fas fa-user"></i>個人</a>
                  </li>
                  <li class="nav-item ">
                      <p class="nav-link active"><i class="fas fa-coins"></i>T幣： {{ coin }}</p>
                  </li>
                  <li class="nav-item justify-content-end right">                      
                    <a class="btn btn-success btn-lg" href="{% url 'personal:log_out' %}" role="button">登出</a>
                </li>
                  {% else %}
                  <li class="nav-item justify-content-end right">                      
                      <a class="btn btn-success btn-lg" href="{% url 'personal:login' %}" role="button">登入</a>
                      <a class="btn btn-success btn-lg" href="{% url 'personal:register' %}" role="button">註冊</a>
                  </li>
                  {% endif %}    
                </div>
              </ul>
            </div>
          </div>
        </nav>
  </div>
</header>