Happy_T_Education_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('camp/', include('camp.urls')),
    path('course/', include('course.urls')),
    path('event/', include('event.urls')),
    path('personal/', include('personal.urls')),
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
]

camp/urls.py
from django.urls import path

from . import views

app_name = 'camp'

urlpatterns = [
    path('campList/', views.List, name='List'),
    path('campDetail/', views.Detail, name='Detail'),
    path('new/', views.new, name='new'),
    path('join/', views.join, name='join'),
]

personal/urls.py
from django.urls import path

from . import views

app_name = 'personal'

urlpatterns = [
    path('', views.userProfile, name='userProfile'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('register/saveAccount/', views.saveAccount, name='saveAccount'),
    path('login/authenticateAccount/', views.authenticateAccount, name='authenticateAccount'),
    path('log_out/', views.log_out, name='log_out'),
]

personal/models.py
from django.db import models
from django.conf import settings
from django.db import models

class Teacher(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=None
    )

    @property
    def showIdentity(self):
        return "Teacher"

    def __str__(self):
        return self.user.username

class Student(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=None
    )

    @property
    def showIdentity(self):
        return "Student"

    def __str__(self):
        return self.user.username

class Coin(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=None
    )

    coin = models.IntegerField(u"T幣數", default=5)

    @property
    def showBalance(self):
        return self.coin

    def __str__(self):
        return self.user.username

personal/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth import authenticate, login as auth_login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import *

@login_required(login_url="personal:login")
def userProfile(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
        context['username'] = request.user.username
    return render(request, 'personal/userProfile.html', context=context)

def register(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'personal/register.html', context=context)

def login(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
    return render(request, 'personal/login.html', context=context)

def saveAccount(request):
    if User.objects.filter(username = request.POST['username']) or User.objects.filter(email = request.POST['email']):
        raise Http404("username or email already exists")
    else:
        user = User.objects.create_user(
            request.POST['username'],
            request.POST['email'],
            request.POST['password'],
        )
        user.save()
        c = Coin(user=user)
        c.save()
        if request.POST['options'] == 'teacher':
            t = Teacher(user=user)
            t.save()
        elif request.POST['options'] == 'student':
            s = Student(user=user)
            s.save()
        return HttpResponseRedirect(reverse('personal:login'))

def authenticateAccount(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        auth_login(request, user)
        return HttpResponseRedirect(reverse('index:index'))
    else:
        raise Http404("The account does not exist")

def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('personal:login'))

personal/templates/personal/login.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="sign">
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2><i class="fas fa-user-circle"></i>Sign in</h2>
                </div>
            </div>
        </div>
        
    </div>
    <div class="jumbotron">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-4 text-start">
                    <form action="{% url 'personal:authenticateAccount' %}" method="POST">
                        {% csrf_token %}
                        <br>
                        <p>使用者名稱</p>
                        <div class="input-group input-group-md">
                            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Your Name" name="username" pattern="^[a-zA-Z][0-9a-zA-Z_]*" title="此帳號名稱不可能存在" required>
                        </div>
                        <p>密碼</p>
                        <div class="input-group input-group-md">
                            <input id="pass" type="password" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Password" name="password" pattern="^((?=.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*|(?=.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!\u0022#$%&'()*+,./:;<=>?@[\]\^_`{|}~-]).*)" minlength="8" title="此密碼不可能存在" required>
                        </div>
                        <br>
                        <input type="submit" class="btn btn-success btn-lg" value="登入">
                    </form>
                    <p>還沒有帳號嗎?<span>快去<a href="{% url 'personal:register' %}">註冊</a>一個吧</span></p>
                </div>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        
    </div>
    <div></div>
</section>
{% endblock %}

personal/templates/personal/register.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block script %}
<script>
    function checkPass(button) {
        let p1 =  document.getElementById("pass");
        let p2 =  document.getElementById("re-pass");

        if(p1.value == p2.value) {
            button.type = "submit";
        } else {
            alert("密碼與密碼確認欄位的輸入並不相符。\n請重新輸入");
            p1.value = "";
            p2.value = "";
            return;
        }
    }
</script>
{% endblock %}
{% block content %}
<section class="sign">
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h2><i class="fas fa-user-circle"></i>Sign up</h2>
                </div>
            </div>
        </div>
        
    </div>
    <div class="jumbotron">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-4 text-start">
                    <form action="{% url 'personal:saveAccount' %}" method="POST">
                        {% csrf_token %}
                        <br>
                        <p>使用者名稱</p>
                        <div class="input-group input-group-md">
                            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Your Name" name="username" pattern="^[a-zA-Z][0-9a-zA-Z_]*" title="帳號名稱開頭不可為數字，且內容只可為英文大小寫其中不可含有特殊字元(除了底線_)" required>
                        </div>
                        <p>電子郵件</p>
                        <div class="input-group input-group-md">
                            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Your Email" name="email" pattern="^\w+((-\w+)|(\.\w+))*[@][A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z]{2,4}$" title="此電子郵件地址無效。請務必確認其格式為 example@email.com" required>
                        </div>
                        <p>密碼</p>
                        <div class="input-group input-group-md">
                            <input id="pass" type="password" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Password" name="password" pattern="^((?=.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*|(?=.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!\u0022#$%&'()*+,./:;<=>?@[\]\^_`{|}~-]).*)" minlength="8" title="請最少輸入8位以上的大小寫英文與數字以及特殊符號" required>
                        </div>
                        <p>確認密碼</p>
                        <div class="input-group input-group-md">
                            <input id="re-pass" type="password" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="Repeat your password" pattern="^((?=.{8,}$)(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).*|(?=.{8,}$)(?=.*\d)(?=.*[a-zA-Z])(?=.*[!\u0022#$%&'()*+,./:;<=>?@[\]\^_`{|}~-]).*)" minlength="8" title="請最少輸入8位以上的大小寫英文與數字以及特殊符號" required>
                        </div>
                        <br>
                        <input type="radio" class="btn-check" name="options" value="student" id="primary-outlined" autocomplete="off" checked>
                        <label class="btn btn-outline-primary" for="primary-outlined"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>Student</label>

                        <input type="radio" class="btn-check" name="options" value="teacher" id="warning-outlined" autocomplete="off">
                        <label class="btn btn-outline-warning" for="warning-outlined"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-eyeglasses" viewBox="0 0 16 16">
                            <path d="M4 6a2 2 0 1 1 0 4 2 2 0 0 1 0-4zm2.625.547a3 3 0 0 0-5.584.953H.5a.5.5 0 0 0 0 1h.541A3 3 0 0 0 7 8a1 1 0 0 1 2 0 3 3 0 0 0 5.959.5h.541a.5.5 0 0 0 0-1h-.541a3 3 0 0 0-5.584-.953A1.993 1.993 0 0 0 8 6c-.532 0-1.016.208-1.375.547zM14 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0z"/>
                        </svg>Teacher</label>
                        <br>
                        <br>
                        <input type="button" class="btn btn-success btn-lg" value="註冊" onclick="checkPass(this);">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="jumbotron">
        
    </div>
    <div></div>
</section>
{% endblock %}

personal/templates/personal/userProfile.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section id="user">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-10 offset-md-2">
                <div class="row">
                    <div class="col-md-5">
                        {% load static %}
                        <img src="{% static 'pic/replace.png' %}">
                    </div>
                    <div class="col-md-5 text-start">
                        <h2>{{username}}</h2>
                        <br>
                        <p><i class="fas fa-coins"></i>T幣： {{ coin }}</p>
                    </div>
                </div>
                <div class="row text-start distence">
                    <h2>Badge</h2>
                    <hr>
                </div>

            </div>    
        </div>
    </div>
</section>
{% endblock %}