Happy_T_Education_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('camp/', include('camp.urls')),
    path('course/', include('course.urls')),
    path('event/', include('event.urls')),
    path('personal/', include('personal.urls')),
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
]

camp/urls.py
from django.urls import path

from . import views

app_name = 'camp'

urlpatterns = [
    path('campList/', views.List, name='List'),
    path('campDetail/', views.Detail, name='Detail'),
    path('new/', views.new, name='new'),
    path('join/', views.join, name='join'),
]

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('course/', views.course, name='course'),
    path('problem/', views.problem, name='problem'),
    path('new/', views.new, name='new'),
    path('detail/', views.detail, name='detail'),
    path('detail/check/', views.check, name='check'),
]

course/models.py
from django.db import models
from personal.models import Teacher, Student
from django.conf import settings

class Course(models.Model):
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default="教師")
    student = models.ManyToManyField(Student, default="學生")

    CATEGORY = (('國文', '國文'),('數學', '數學'),('英文', '英文'),('自然', '自然'),('社會', '社會'),('技術', '技術'))
    categories = models.CharField(u'科目',choices=CATEGORY,max_length=10,default='請選擇科目')
    name = models.CharField(u"課程名稱",max_length=20)
    descritions = models.CharField("介紹",max_length=5000)
    image = models.ImageField(u'課程封面',upload_to='picture/%Y/%m/%d/')
    lessons = models.IntegerField(u"課堂數")
    cost = models.IntegerField(u"T幣")

    def __str__(self):
        return self.name

class Problem(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=None
    )
    problem = models.CharField(u"問題",max_length=500)

    def __str__(self):
        return self.problem

class Answer(models.Model):
    problem = models.ForeignKey(
        Problem,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        default=None
    )
    answer = models.CharField(u"解答",max_length=500)

    def __str__(self):
        return self.answer

course/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Course

@login_required(login_url="personal:login")
def course(request):
    Course.objects.order_by('-pk')
    context = {
        'Courses_List' : Course.objects.order_by('-pk')
    }
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'course/course.html', context=context)

@login_required(login_url="personal:login")
def problem(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'course/problem.html', context=context)

@login_required(login_url="personal:login")
def new(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'course/new.html', context=context)

@login_required(login_url="personal:login")
def detail(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'course/detail.html', context=context)

@login_required(login_url="personal:login")
def check(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'course/check.html', context=context)

course/templates/course/check.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section id="join">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8 text-center">
                <h3>加入課程將會扣除5T幣，是否繼續?</h3>
                <a class="btn btn-primary btn-lg" href="#" role="button">是</a>
                <a class="btn btn-danger btn-lg" href="#" role="button">否</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

course/templates/course/course.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="class">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2>課程資訊</h2>
                <h4 class="text-end left"><a href="{% url 'course:new' %}"><i class="fas fa-plus"></i>新增課程</a></h4>
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">
                      <li class="nav-item btnall">
                        <a class="nav-link active" aria-current="page" href="#">全部</a>
                        </li>
                        <li class="nav-item btn1">
                            <a class="nav-link" href="#">語文</a>
                        </li>
                        <li class="nav-item btn2">
                            <a class="nav-link" href="#">數學</a>
                        </li>
                        <li class="nav-item btn3">
                            <a class="nav-link" href="#">英文</a>
                        </li>
                        <li class="nav-item btn4">
                            <a class="nav-link" href="#">自然</a>
                        </li>
                        <li class="nav-item btn5">
                            <a class="nav-link" href="#">社會</a>
                        </li>
                        <li class="nav-item btn6">
                            <a class="nav-link" href="#">技術</a>
                        </li>
                    </div>
                  </nav>
                <div class="row">
                    <div class="col-md-3 text-start chinese active gcontent">
                        <div class="outer">                       
                            <a href="{% url 'course:detail' %}">
                                <div class="inner">
                                    {% load static %}
                                    <img src="{% static 'pic/replace.png' %}">
                                    <div class="innertext">
                                        <span>可報名</span>
                                    </div>
                                </div>
                                <div class="down">
                                    <h3>吳宏國文</h3>
                                    <p>授課教師：吳柏宏</p>
                                    <span>課堂數：12</span>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% for course in Courses_List %}
                    <div class="col-md-3 text-start chinese active gcontent">
                        <div class="outer">
                            <a href="{% url 'course:detail' %}">
                                <div class="inner">
                                    {% load static %}
                                    <img src="{% static 'pic/replace.png' %}">
                                    <div class="innertext">
                                        <span>可報名</span>
                                    </div>
                                </div>
                                <div class="down">
                                    <h3>{{course.name}}</h3>
                                    <p>授課教師：{{course.teacher}}</p>
                                    <span>課堂數：{{course.lessons}}</span>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

course/templates/course/detail.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="info">
    <div class="container">
        <div class="row">
            <div class="col-md-6 ">
                <img src="https://images.edexlive.com/uploads/user/imagelibrary/2019/3/26/original/thesisc.jpg" alt="">
            </div>
            <div class="col-md-6">
                <div class="center">
                    <p><i class="fas fa-flag"></i>吳宏國文</p>
                    <p><i class="fas fa-clock"></i>總計12堂，24小時</p>
                    <a class="btn btn-primary btn-lg" href="{% url 'course:check' %}" role="button">報名參與</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h3>課程資訊</h3>
                <p>本次課程將會帶領同學上完中國文學，並在最後有個小測驗</p>
            </div>
        </div>
    </div>
</section>
{% endblock %}

course/templates/course/new.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="info">
    <div class="container">
        <div class="row">
            <div class="col-md-6 ">
                {% load static %}
                <img src="{% static 'pic/new.png' %}" >
                <form action="#">
                    <label class="btn btn-primary">
                        <input id="upload_img" style="display:none;" type="file">
                        <i class="fa fa-photo"></i> 上傳課程預覽圖
                    </label>
                </form>
            </div>
            <div class="col-md-6">       
                <div class="center">
                    <form action="#">
                        <br>
                        <i class="fas fa-book-open"></i>
                        <div class="input-group input-group-md">
                            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="課程名稱">
                        </div>
                        <i class="fas fa-user-circle"></i>
                        <div class="input-group input-group-md">
                            <div class="input-group input-group-md">
                                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="教師名稱">
                            </div>
                        </div>
                        <i class="fas fa-calendar-alt"></i>
                        <div class="input-group input-group-md">
                            <div class="input-group input-group-md">
                                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="課堂數">
                            </div>
                        </div>
                        <div class="input-group input-group-md">
                            <i class="fas fa-coins"></i>
                            <div class="input-group input-group-md">
                                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="收取的T幣">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1" class="form-label">課程介紹</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                        <br>
                        <a class="btn btn-success btn-lg" href="#" role="button">創建</a>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
               <div>
                   <h3>上傳課程內容</h3>
                    <label class="btn btn-primary">
                    <input id="upload_img" style="display:none;" type="file">
                    <i class="fa fa-photo"></i> 上傳影片
                    </label>
                </div>                 
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

course/templates/course/problem.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section id="question">
    <div class="container">
        <div class="row ">  
            <div class="col-md-8 offset-md-2 text-center bord">
                <h2>題目問答</h2>
                <h4 class="text-end left"><a href="#"><i class="fas fa-plus"></i>詢問問題</a></h4>
                <div class="row">
                    <div class="col-md-12 shadow">
                        <div class="row">
                            <div class="col-md-4 text-center">
                                {% load static %}
                                <img src="{% static 'pic/replace.png' %}">
                                <h4>Peter</h4>
                            </div>
                            <div class="col-md-8 text-start">
                                <h4>數學問題</h4>
                                <p>求解 5!+3! 為多少</p>
                            </div>
                        </div>
                        <hr>
                        <div class="down text-start col-md-12">
                            <div class="input-group input-group-md">
                                <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-mg" placeholder="你的回答">
                                <a class="btn btn-primary btn-lg" href="#" role="button">提交</a>
                            </div>
                        </div>                       
                    </div>                        
                </div>           
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}