Happy_T_Education_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('camp/', include('camp.urls')),
    path('course/', include('course.urls')),
    path('event/', include('event.urls')),
    path('personal/', include('personal.urls')),
    path('index/', include('index.urls')),
    path('admin/', admin.site.urls),
]

camp/urls.py
from django.urls import path

from . import views

app_name = 'camp'

urlpatterns = [
    path('campList/', views.List, name='List'),
    path('campDetail/', views.Detail, name='Detail'),
    path('new/', views.new, name='new'),
    path('join/', views.join, name='join'),
]

camp/models.py
from django.db import models
from personal.models import Teacher, Student

class Camp(models.Model):
    contractor = models.ForeignKey(Teacher, on_delete=models.CASCADE, default="承辦人")
    applicant = models.ManyToManyField(Student, default="參加者")

    name = models.CharField(u'營隊名稱',max_length=20)
    date = models.DateTimeField('舉辦日期', null=True)
    pos = models.CharField(u'營隊地點',max_length=20)
    cost = models.IntegerField(u'費用')
    descritions = models.TextField(u'介紹',max_length=1000)

    def __str__(self):
        return self.name

# Create your models here.

camp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required(login_url="personal:login")
def List(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'camp/list.html', context=context)

@login_required(login_url="personal:login")
def Detail(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'camp/detail.html', context=context)

@login_required(login_url="personal:login")
def new(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'camp/new.html', context=context)

@login_required(login_url="personal:login")
def join(request):
    context = {}
    if request.user.is_authenticated:
        context['is_authenticated'] = True
        context['coin'] = request.user.coin.coin
    return render(request, 'camp/join.html', context=context)

camp/templates/camp/detail.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="info">
  <div class="container">
      <div class="row">
          <div class="col-md-6 ">
              <div id="carouselExampleInterval" class="carousel slide box" data-bs-ride="carousel">
                  <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="10000">
                      <img src="https://pic.pimg.tw/newbrue/1464098717-1580541710_n.jpg" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item" data-bs-interval="2000">
                      <img src="https://www.pyps.ntpc.edu.tw/var/file/0/1000/img/1.jpg" class="d-block w-100" alt="...">
                    </div>
                  </div>
                  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                  </button>
                  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                  </button>
                </div>
          </div>
          <div class="col-md-6">
              <div class="center">
                  <p><i class="fas fa-flag"></i>池上之美</p>
                  <p><i class="fas fa-clock"></i>2021年1月15日到1月21日</p>
                  <p><i class="fas fa-user"></i>承辦人：王德芳</p>
                  <p><i class="fas fa-phone"></i>聯絡資訊：09-xxxxxxxx</p>
                  <a class="btn btn-primary btn-lg" href="{% url 'camp:join' %}" role="button">報名參與</a>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-12"> 
              <p>活動內容  帶領小朋友們走入池上 體驗農家的生活、種稻的辛苦 了解 粒粒皆辛苦</p>
          </div>
      </div>
  </div>
</section>
{% endblock %}

camp/templates/camp/join.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="info">
    <div class="container">
        <div class="row">
            <div class="col-md-6 small">
                <img src="https://upload.wikimedia.org/wikipedia/commons/7/74/%E5%8F%B0%E6%9D%B1%E6%B1%A0%E4%B8%8A%E7%A8%BB%E7%A9%97%E7%A7%8B%E6%94%B6.jpg" style="width: 100%;">
            </div>
            <div class="col-md-6">       
                <div class="center">
                    <form class="row g-3 needs-validation" novalidate>
                        <div class="col-md-4">
                          <label for="validationCustom01" class="form-label">名字</label>
                          <input type="text" class="form-control" id="validationCustom01" required>
                        </div>
                        <div class="col-md-4">
                          <label for="validationCustom02" class="form-label">身分證</label>
                          <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-4">
                            <label for="validationCustom02" class="form-label">電話</label>
                            <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-4">
                            <label for="validationCustom02" class="form-label">緊急聯絡人電話</label>
                            <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-2">
                          <label for="validationCustom05" class="form-label">年級</label>
                          <input type="text" class="form-control" id="validationCustom05" required>                             
                        </div>
                        <div class="col-md-2">
                            <label for="validationCustom05" class="form-label">葷素</label>
                            <input type="text" class="form-control" id="validationCustom05" required>                             
                          </div>
                        <div class="col-md-4">
                            <label for="validationCustom05" class="form-label">匯款帳號末五碼</label>
                            <input type="text" class="form-control" id="validationCustom05" required>                             
                        </div>
                        <div class="col-md-12 ">
                            <a class="btn btn-success btn-lg" href="#" role="button">報名</a>
                        </div>                          
                      </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

camp/templates/camp/list.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="class">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2>營隊資訊</h2>
                <h4 class="text-end left"><a href="{% url 'camp:new' %}"><i class="fas fa-plus"></i>新增營隊</a></h4>
                <div class="row">       
                    <div class="col-md-3 text-start">
                        <div class="outer">                       
                            <a href="{% url 'camp:Detail' %}">
                                <div class="inner">
                                    {% load static %}
                                    <img src="{% static 'pic/replace.png' %}">
                                    <div class="innertext">
                                        <span>可報名</span>
                                    </div>
                                </div>
                                <div class="down">
                                    <h3>池上之美</h3>
                                    <p><i class="fas fa-map-marker-alt">台東縣池上鄉</i></p>
                                    <p>參加對象：國小3-6年級</p>
                                    <span><i class="fas fa-clock"></i>2022年3月14日</span>
                                </div>
                            </a>
                        </div>
                    </div>   
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

camp/templates/camp/new.html
{% extends 'base.html' %}
{% block title %} 快樂T教育平台 {% endblock %}
{% block content %}
<section class="info">
    <div class="container">
        <div class="row">
            <div class="col-md-6 ">
                {% load static %}
                <img src="{% static 'pic/new.png' %}" >
                <form action="#">
                    <label class="btn btn-primary">
                        <input id="upload_img" style="display:none;" type="file">
                        <i class="fa fa-photo"></i> 上傳營隊預覽圖
                    </label>
                </form>
            </div>
            <div class="col-md-6">       
                <div class="center">
                    <form class="row g-3 needs-validation" novalidate>
                        <div class="col-md-4">
                          <label for="validationCustom01" class="form-label">營隊名稱</label>
                          <input type="text" class="form-control" id="validationCustom01" required>
                        </div>
                        <div class="col-md-4">
                          <label for="validationCustom02" class="form-label">承辦人名稱</label>
                          <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-4">
                            <label for="validationCustom02" class="form-label">承辦人電話</label>
                            <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-6">
                          <label for="validationCustom03" class="form-label">營隊地點</label>
                          <input type="text" class="form-control" id="validationCustom03" required>
                        </div>
                        <div class="col-md-3">
                            <label for="validationCustom02" class="form-label">營隊費用</label>
                            <input type="text" class="form-control" id="validationCustom02" value="" required>  
                        </div>
                        <div class="col-md-3">
                          <label for="validationCustom05" class="form-label">參加對象</label>
                          <input type="text" class="form-control" id="validationCustom05" required>                             
                        </div>
                        <div class="col-md-3">
                            <label for="validationCustom05" class="form-label">營隊限制人數</label>
                            <input type="text" class="form-control" id="validationCustom05" required>                             
                          </div>
                        <div class="col-md-9">
                            <label for="validationCustom05" class="form-label">日期</label>
                            <input type="text" class="form-control" id="validationCustom05" required>                             
                        </div>
                        <div class="col-md-12">
                            <label for="validationCustom05" class="form-label">匯款銀行帳戶</label>
                            <input type="text" class="form-control" id="validationCustom05" required>                             
                        </div>
                        <div class="col-md-12">
                            <div class="mb-3">
                                <label for="exampleFormControlTextarea1" class="form-label">課程介紹</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                            </div>
                        </div>
                        <div class="col-md-4 text-start">
                            <a class="btn btn-success btn-lg" href="#" role="button">創建</a>
                        </div>                          
                      </form>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block bodyScript %}
{% load static %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}